# AppVeyor CI build file, https://ci.appveyor.com/project/HangfireIO/cronos

#---------------------------------#
#    environment configuration    #
#---------------------------------#

version: build.{build}

image:
  - Visual Studio 2022
#  - Ubuntu2204

environment:
  SIGNPATH_API_TOKEN:
    secure: J4NQ06YnHkzn0R+ZXz+TGbHHnfsp2KHeWzAeFr3oPKsvZnpkYuZNv5L118BcEx3B

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - pwsh: Install-PSResource -Name SignPath -TrustRepository
  - sh: nuget locals all -clear

build_script:
  - cmd: build.bat sign
  - sh: dotnet test -c:release -f:net6.0 tests/Cronos.Tests

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: +DJ6AMelkHOo9gVAAzJ85gRcku6qX+Z4I+0EO2uYrul8tg/v+b/jHxZoTCp9/AWT
    on:
      appveyor_repo_tag: true
